services:
  - type: web
    name: inventa-erp-demo
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    branch: main
    region: oregon
    runtime: python
    repo: https://github.com/kwetu-stack/inventa-ERP
    autoDeploy: true
